### ISSUE TITLE
CornerStone - A use case , multiple raft clusters

### ISSUE THREAD

**Issue by yashhema** [datatechnology/cornerstone#23]
Hello,
Can you please provide your inputs -
Consider I have 5 servers (S1,S2,S3,S4,S5) , and 7 tasks which are running on these servers. Each task needs 2 replicas.
For task T1 - I can have S1,S2,S3 where S1 is the leader
For task T2 - I can have S2,S1,S3 where S2 is the leader
and so on. Its possible one of the server goes down, then I should be able to add one of the existing server like say if S1 goes down, I should be able to S4 instead. 

Can cornerstone be used for such kind of use case, do you have some pointers for this.
regards

**Comment by datatechnology** [comment]
Are you referring S1, S2, S3, S4 and S5 in the same Raft cluster? if yes, then there would be only one leader at a time. So, I don't quite understand your question

**Comment by yashhema** [comment]
Sorry, I was not clear . Consider i have 5 servers S1 to S5. 
I want to run 5 raft cluster , each with its own leader (basically each Server is the leader of its data which it has to store , and replicates it to 2 other servers)
Something like Multiraft (Atomix  - https://atomix.io/docs/latest/user-manual/cluster-management/partition-groups/)

**Comment by datatechnology** [comment]
@yashhema If I understand you correctly, you want run 5 instances of raft on each node and use 3 as the cluster size, so with S1, S2, and S3, you will be able to get 5 clusters with 3 nodes in each cluster, and yes, cornerstone can support this scenario. Then, if say, S1 goes down, then all clusters are running with two nodes only, that's risky, the cluster will be out of quorum if any of S2 and S3 goes down again, and so, to your question, you want to add S4 to all clusters, and also YES, cornerstone can support that, here is what you gotta do,
1. Remove S1 from all five clusters by sending remove server command to all 5 clusters.
2. After the command has been executed (means committed), then
3. Start five instances of raft on S4 with cornerstone
4. Send command to all five clusters to ask to add S4 to the cluster
5. After that is committed, all five clusters will send invite to join command to S4, and S4 will be eventually added to all five clusters
Now, all five clusters will have S2, S3 and S4 as the members
