### ISSUE TITLE
Why the dest of resp_msg is set to leader but not the src of req_msg?

### ISSUE THREAD

**Issue by LuminousXLB** [datatechnology/cornerstone#26]
I'm trying to do the bootstrap like this:

- Startup a single server (id=1). There's only one server (i.e. itself) in the config.
- Startup another server (id=2).
- Send an `add_server_request` with `LastLogIndex=0, LastLogTerm=0, EntriesLength=1, CommitIndex=0 and Term=0` to server 1 using a dedicated client with id=0.
- Then I found that the dest in the response message generated by server 1 was set as server 1 (i.e. itself) but not server 0 (the source of the request message).

Related code is [here](https://github.com/datatechnology/cornerstone/blob/master/src/raft_server.cxx#L1155)

**Comment by andy-yx-chen** [comment]
That's historical issue that the dst field is reused for indicating who is the current leader in case of the request is received from a client library (not the peer), a better way, though, should have a separate message protocol between cli and server, which is still a plan, we may make more changes to the library to make it easier to use
