### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [datatechnology/cornerstone#42]
I would like to point out that identifiers like “[`_CORNERSTONE_HXX_`](https://github.com/datatechnology/cornerstone/blob/86a36b4ff189f126b3c9324b48227d948864c6e2/include/cornerstone.hxx#L18 "Update candidate")” and “[`_RAFT_SERVER_HXX_`](https://github.com/datatechnology/cornerstone/blob/ced3e3220548e5cbf27ad488e03b5e39cbfa5816/include/raft_server.hxx#L18 "Another update candidate")” [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by datatechnology** [comment]
would you like to contribute?
